apiVersion: v1
kind: Secret
metadata:
  name: vault-secret
  namespace: bpm-core-staging
type: Opaque
stringData:
  VAULT_HOST: https://vault.rytass.org
  VAULT_ACCOUNT: bpm-core-staging
  VAULT_PASSWORD: <vault-userpass-password>
  VAULT_PATH: bpm_core/staging
